/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package pms;
import java.sql.*;
/**
 *
 * @author DELL
 */
public class NewItemDetails extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewItemDetails
     */
    public NewItemDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Save = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        ItemCode = new javax.swing.JTextField();
        ItemName = new javax.swing.JTextField();
        ItemType = new javax.swing.JTextField();
        Company = new javax.swing.JTextField();
        Size = new javax.swing.JTextField();
        ItemPrice = new javax.swing.JTextField();
        Quantity = new javax.swing.JTextField();
        GST = new javax.swing.JTextField();
        Purchase = new javax.swing.JTextField();
        MRP = new javax.swing.JTextField();
        Exit = new javax.swing.JButton();
        Invoice = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setAutoscrolls(true);

        jLabel1.setText("Purchase Details");

        jLabel2.setText("Item Code");

        jLabel3.setText("Item Name");

        jLabel4.setText("Itme Type");

        jLabel5.setText("Company");

        jLabel6.setText("Box size");

        jLabel7.setText("Trade Price");

        jLabel8.setText("Quantity");

        jLabel9.setText("GST");

        jLabel10.setText("Purchase Price");

        jLabel11.setText("MRP");

        Save.setText("Save Data");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        jLabel12.setText("Invoice No");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Save)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(70, 70, 70)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(1, 1, 1)))
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Save)
                .addGap(0, 50, Short.MAX_VALUE))
        );

        ItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemNameActionPerformed(evt);
            }
        });

        MRP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MRPActionPerformed(evt);
            }
        });

        Exit.setText("Exit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Exit)
                    .addComponent(ItemCode, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(ItemName)
                    .addComponent(ItemType)
                    .addComponent(Company)
                    .addComponent(Size)
                    .addComponent(ItemPrice)
                    .addComponent(Quantity)
                    .addComponent(GST)
                    .addComponent(Purchase)
                    .addComponent(MRP)
                    .addComponent(Invoice))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(Invoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(ItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ItemType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Company, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ItemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Purchase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MRP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Exit)))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemNameActionPerformed

    private void MRPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MRPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MRPActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed

                Connection con=null;
		PreparedStatement pstmt1=null,pstmt2=null,pstmt3=null;
                Statement stmt=null;
                
		ResultSet rs=null;
                
                int invoiceno=Integer.parseInt(Invoice.getText());
                int itemcode=Integer.parseInt(ItemCode.getText());
		String itemname=ItemName.getText();
		String itemtype=ItemType.getText();
		String  company=Company.getText();
		int boxsize=Integer.parseInt(Size.getText());
		int tradeprice=Integer.parseInt(ItemPrice.getText());
                int quantity=Integer.parseInt(Quantity.getText());
		int gst=Integer.parseInt(GST.getText());
                int purchaserate=Integer.parseInt(Purchase.getText());
                int mrp=Integer.parseInt(MRP.getText());

		try
		{
                    
			Class.forName("com.mysql.jdbc.Driver");
		
			con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pms","root","1234");
                        
                        
                        stmt = con.createStatement();

			rs = stmt.executeQuery("Select * from purchase where itemcode="+itemcode);
                        
                        if(rs.next())
                        {                       
                        
                        
	
			pstmt1=con.prepareStatement("insert into medicine values(?,?,?,?,?,?,?,?,?,?,?)");

                        pstmt1.setInt(1,invoiceno);
			pstmt1.setInt(2,itemcode);
			pstmt1.setString(3,itemname);
			pstmt1.setString(4,itemtype);
			pstmt1.setString(5,company);
			pstmt1.setInt(6,boxsize);
			pstmt1.setInt(7,tradeprice);
                        pstmt1.setInt(8,quantity);
			pstmt1.setInt(9,gst);
                        pstmt1.setInt(10,purchaserate);
                        pstmt1.setInt(11,mrp);
      
			pstmt1.executeUpdate();
                        
                  //      System.out.println("Data Inserted");
                        
                        
                        
                        
                        pstmt3=con.prepareStatement("update stock set Quantity=? where itemcode="+itemcode);

                        
			pstmt3.setInt(1,quantity);
			
			pstmt3.executeUpdate();
                        
			System.out.println("Data Updated");
                        
                        }
                        
                        
                        else
                        {
                        
                            pstmt1=con.prepareStatement("insert into purchase values(?,?,?,?,?,?,?,?,?,?,?)");

			
                        pstmt1.setInt(1,invoiceno);    
                        pstmt1.setInt(2,itemcode);
			pstmt1.setString(3,itemname);
			pstmt1.setString(4,itemtype);
			pstmt1.setString(5,company);
			pstmt1.setInt(6,boxsize);
			pstmt1.setInt(7,tradeprice);
                        pstmt1.setInt(8,quantity);
			pstmt1.setInt(9,gst);
                        pstmt1.setInt(10,purchaserate);
                        pstmt1.setInt(11,mrp);

			pstmt1.executeUpdate();
                        
                            
                            
                        pstmt2=con.prepareStatement("insert into stock values(?,?,?,?,?,?,?,?,?,?,?)");

                        pstmt2.setInt(1,invoiceno);
			pstmt2.setInt(2,itemcode);
			pstmt2.setString(3,itemname);
			pstmt2.setString(4,itemtype);
			pstmt2.setString(5,company);
			pstmt2.setInt(6,boxsize);
			pstmt2.setInt(7,tradeprice);
                        pstmt2.setInt(8,quantity);
			pstmt2.setInt(9,gst);
                        pstmt2.setInt(10,purchaserate);
                        pstmt2.setInt(11,mrp);

			pstmt2.executeUpdate();
                        
                        System.out.println("Data Inserted");
               
                        }

		}

		catch(ClassNotFoundException | SQLException ex)
		{
			System.out.println(ex);
		}
    }//GEN-LAST:event_SaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Company;
    private javax.swing.JButton Exit;
    private javax.swing.JTextField GST;
    private javax.swing.JTextField Invoice;
    private javax.swing.JTextField ItemCode;
    private javax.swing.JTextField ItemName;
    private javax.swing.JTextField ItemPrice;
    private javax.swing.JTextField ItemType;
    private javax.swing.JTextField MRP;
    private javax.swing.JTextField Purchase;
    private javax.swing.JTextField Quantity;
    private javax.swing.JButton Save;
    private javax.swing.JTextField Size;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
